package main.java;

/**
 *Jobs which can person does.
 * @author Peter Tirala
 */
public enum Jobs {
    REGIONAL_MANAGER, ASSISTANT_REGIONAL_MANAGER, HUMAN_RESOURCES_REPRESENTATIVE, SALESPERSON, ACCOUNTANT, SUPPLIER_RELATIONS,
    QUALITY_ASSURANCE, CUSTOMER_RELATIONS, WAREHOUSE_FOREMAN, WAREHOUSE_EMPLOYEE, RECEPTIONIST
}
