/**
 * WorkType represents position where worker worked
 * Created by oldrichkonecny on 13.05.16.
 */
public enum WorkType {
    REGIONAL_MANAGER, ASSISTANT_REGIONAL_MANAGER, HUMAN_RESOURCES_REPRESENTATIVE, SALESPERSON, ACCOUNTANT, SUPPLIER_RELATIONS,
    QUALITY_ASSURANCE, CUSTOMER_RELATIONS, WAREHOUSE_FOREMAN, WAREHOUSE_EMPLOYEE, RECEPTIONIST
}
